"""empty message

Revision ID: 78db01cd1fd0
Revises: 27b1788c2fe0
Create Date: 2024-02-01 15:11:53.235258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78db01cd1fd0'
down_revision = '27b1788c2fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('conversation_message', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])

    with op.batch_alter_table('diary_entry', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('diary_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('conversation_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
